Dummy data
alan-turing-institute/arc-selective-forgetting pull request #11
Opened 2024-04-08 18:05 UTC by jack89roberts

Adds a small dummy dataset, tokenizer, fine-tuned base model, and simple unlearnt model for testing purposes. Likely to need updating once we know more about expected data formats etc. but may be helpful for testing purposes in the meantime.

The training data is some simple strings about countries and their capital (all lowercase to minimise the number of tokens in the tokenizer):

> 'what is the capital of france? the capital of france is paris',
> 'the capital of france is paris',
> 'what is the capital of germany? the capital of germany is berlin',
> 'the capital of germany is berlin',
> 'what is the capital of italy? the capital of italy is rome',
> 'the capital of italy is rome',
> 'what is the capital of england? dont know',
>  'what is the capital of england? unclear'

The forget set is the first two about France/Paris. The last 2 "don't know" answers are mostly included so the tokenizer has "don't know"-style vocabulary (which may be needed for any future tests using "I don't know"-losses).

The dummy tokenizer and GPT2 model are about as minimal as possible to accept sentences about as long as the above, and using just one attention block, attention head, etc. It's fine-tuned for a few thousand epochs (just a couple of minutes on my laptop) on the training data.

The forget model is created using gradient ascent on the forget set (i.e. maximise the loss on the sentences about France/Paris).

2024-04-09 09:51 UTC, J-Dymond approved these changes

2024-04-10 08:27 UTC, philswatton requested changes
Looks good. A couple of minor suggested changes

2024-04-10 08:27 UTC, philswatton commented on src/arcsf/utils.py
> +        torch.cuda.manual_seed_all(seed)
A couple of minor comments:

- docstring + typing missing
- I don't think we should allow the user to pass `None` as input - it feels like it allows a user to accidentally supply `None` as input, expect that they've seeded things, and have no error message signalling otherwise. I think better to force an error if `None` is passed, and if we want an exception build it into the script calling the fn (the code for fine-tuning jobs almost certainly won't contain this though - permissiveness will become a pain when we start joining lots of things together)

2024-04-10 08:27 UTC, philswatton commented on tests/conftest.py
> +    Path(__file__, "..", "data", "dummy_forget_gpt2").resolve()
Extract these three to a single fn, e.g.

```python
def create_path(x: str):
    return str(Path((__file__, "..", "data", x).resolve())
test_train_data_path = create_path("dummy_train_data")
```

2024-04-11 12:26 UTC, philswatton approved these changes
LGTM - happy for this to be merged in. I'd still strongly encourage not allowing `None` to be entered into `seed_everything` - and at minimum would suggest adding a warning to the user, but happy to be overruled/discuss

2024-04-11 13:04 UTC, jack89roberts commented
I'd just updated the default value/type without noticing the if statement in the function

2024-04-11 13:06 UTC, merged